baseURL = "https://www.renem.net/"
languageCode = "de"
title = "René"
theme = "Detox"
description = "Just my 2 cents…"
MetaDataFormat = "yaml"
disableAliases = true
[blackfriday]
angledQuotes = true
smartypantsQuotesNBSP = true
[outputs]
home = [ "HTML", "RSS", "JSON", "REDIR", "HEADERS"]
[mediaTypes]
[mediaTypes."text/netlify"]
suffix = ""
delimiter = ""
[outputFormats]
[outputFormats.REDIR]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true
[Author]
  name = "René"
  email = "rene@renem.net"
[Params]
  description = "Just my 2 cents…"
  Paginate = 15
  RSSLink = "/post/index.xml"
  RSSLimit = 20
  author = "ReneM" # add your company name
  license = "CC-BY-NC-SA"
  github = "rretsiem" # add your github profile name
  twitter_name = "rretsiem" # add your twitter profile
  email = "rene@renem.net"
  ISO8601 = "2006-01-02T15:04:05+02:00"
  webSub = "https://renem.superfeedr.com/"
[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
[[menu.main]]
        name = "Artikel"
        weight = 1
        pre = "Archive List of Blog Articles"
        identifier = "mainarticles"
        url = "/post"
[[menu.main]]
        name = "Photos"
        weight = 2
        pre = "Photo Beiträge"
        identifier = "mainphotos"
        url = "/photo"
[[menu.main]]
        name = "Microblog"
        weight = 3
        pre = "Short posts and social interactions"
        identifier = "mainmicroblog"
        url = "/microblog"
[[menu.main]]
        name = "PGP"
        weight = 4
        identifier = "mainpgp"
        url = "/pgp"
[[menu.main]]
        name = "About"
        url = "/about"
        pre = "About ReneM"
        identifier = "mainabout"
        weight = 5
#[[menu.main]]
#        name = "Tags"
#        url = "/tags"
#        pre = "All Tags"
#        post = "xs-hide"
#        identifier = "mainalltags"
#        weight = 5
