baseURL = "https://renem.net/"
languageCode = "de"
title = "René"
theme = "Detox"
description = "Just my 2 cents…"
MetaDataFormat = "yaml"
disableAliases = true
[blackfriday]
angledQuotes = true
smartypantsQuotesNBSP = true
[outputs]
home = [ "HTML", "RSS", "JSON", "REDIR", "HEADERS"]
page = ["HTML", "JSON"]
[mediaTypes]
[mediaTypes."text/netlify"]
suffix = ""
delimiter = ""
[outputFormats]
[outputFormats.REDIR]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true
[Author]
  name = "René"
  email = "rene@renem.net"
[Params]
  description = "Just my 2 cents…"
  Paginate = 15
  RSSLink = "/post/index.xml"
  RSSLimit = 20
  author = "René" # add your company name
  license = "CC-BY-NC-SA"
  github = "rretsiem" # add your github profile name
  twitter_name = "rretsiem" # add your twitter profile
  flickr_name = "renene26" # add your flickr username
  instagram = "rene.meister" # add your instagram username
  email = "rene@renem.net"
  ISO8601 = "2006-01-02T15:04:05+02:00"
  webSub = "https://renem.superfeedr.com/"
[sitemap]
  changefreq = "daily"
  priority = 0.5
  filename = "sitemap.xml"
[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
[[menu.main]]
        name = "Artikel"
        weight = 1
        pre = "Archive List of Blog Articles"
        identifier = "mainarticles"
        url = "/post"
[[menu.main]]
        name = "Microblog"
        weight = 3
        pre = "Short posts and social interactions"
        identifier = "mainmicroblog"
        url = "/microblog"
[[menu.main]]
        name = "Archiv"
        weight = 4
        identifier = "mainarchive"
        url = "/archive"
[[menu.main]]
        name = "About"
        url = "/about"
        pre = "About ReneM"
        identifier = "mainabout"
        weight = 5
#[related]
# Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
# threshold = 0
# To get stable "See also" sections we, by default, exclude newer related pages.
#includeNewer = true
# Will lower case keywords in both queries and in the indexes.
#toLower = true
#[[related.indices]]
#name = "categories"
#weight = 150
#[[related.indices]]
#name  = "tags"
#weight = 100
#[[related.indices]]
#name  = "date"
#weight = 10
#pattern = "2006"
