baseURL = "https://renem.net/"
languageCode = "de"
title = "René"
theme = "Detox"
description = "Just my 2 cents…"
MetaDataFormat = "yaml"
disableAliases = true
enableEmoji = true
defaultMarkdownHandler = "goldmark"
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xHTML = false
#[blackfriday]
#  angledQuotes = true
#  smartypantsQuotesNBSP = true
disableKinds = ["RSS"]
[mediaTypes]
[mediaTypes."text/netlify"]
[mediaTypes."application/atom+xml"]
  suffixes = ["xml"]
[outputs]
  home = [ "HTML", "ATOM", "JSON", "REDIR", "HEADERS"]
  page = [ "HTML"]
  section = ["HTML", "ATOM", "JSON"]
  taxonomy = ["HTML", "ATOM", "JSON"] # default = ["HTML", "RSS"]
  term = ["HTML", "ATOM", "JSON"] # default = ["HTML", "RSS"]
[outputFormats]
  [outputFormats.REDIR]
   mediatype = "text/netlify"
   baseName = "_redirects"
   isPlainText = true
   notAlternative = true
  [outputFormats.ATOM]
    mediaType = "application/atom+xml"
    baseName = "index"
    isPlainText = false
    isHTML = false
    noUgly = true
    rel = "alternate"
    notAlternative = true
  [outputFormats.HEADERS]
    mediatype = "text/netlify"
    baseName = "_headers"
    isPlainText = true
    notAlternative = true
sectionPagesMenu = "main"
[Author]
  name = "René"
  email = "rene@renem.net"
[Params]
  description = "Just my 2 cents…"
  Paginate = 20
  RSSLimit = 25
  author = "René" # add your company name
  license = "CC-BY-NC-SA"
  github = "rretsiem" # add your github profile name
  twitter_name = "rretsiem" # add your twitter profile
  flickr_name = "renene26" # add your flickr username
  instagram = "rene.meister" # add your instagram username
  pixelfed = "renem"
  microblog_name = "renem"
  email = "rene@renem.net"
  ISO8601 = "2006-01-02T15:04:05+00:00"
  webSub = "https://renem.superfeedr.com/"
[sitemap]
  changefreq = "daily"
  priority = 0.5
  filename = "sitemap.xml"
[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
[[menu.main]]
        name = "Artikel"
        weight = 1
        identifier = "post"
        url = "/post/"
[[menu.main]]
        name = "Photos"
        weight = 2
        identifier = "photos"
        url = "/photos/"
[[menu.main]]
        name = "Notes"
        weight = 3
        identifier = "notes"
        url = "/notes/"
[[menu.main]]
        name = "Archiv"
        weight = 5
        identifier = "archive"
        url = "/archive/"
[[menu.main]]
        name = "About"
        url = "/about/"
        identifier = "about"
        weight = 6
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.speakerDeck]
    disable = true
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = true
  [privacy.vimeo]
    disable = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
[services]
  [services.twitter]
    disableInlineCSS = true
