baseURL = "https://renem.net/"
languageCode = "de"
title = "René"
theme = "Detox"
description = "Just my 2 cents…"
MetaDataFormat = "yaml"
disableAliases = true
[blackfriday]
angledQuotes = true
smartypantsQuotesNBSP = true
disableKinds = ["RSS"]
[mediaTypes]
[mediaTypes."text/netlify"]
[mediaTypes."application/atom+xml"]
  suffixes = ["xml"]
[outputs]
  home = [ "HTML", "ATOM", "JSON", "REDIR", "HEADERS"]
  page = [ "HTML"]
  section = ["HTML", "ATOM", "JSON"]
[outputFormats]
  [outputFormats.REDIR]
   mediatype = "text/netlify"
   baseName = "_redirects"
   isPlainText = true
   notAlternative = true
  [outputFormats.ATOM]
    mediaType = "application/atom+xml"
    baseName = "index"
    isPlainText = false
    isHTML = false
    noUgly = true
    Rel = "alternate"
    notAlternative = true
  [outputFormats.HEADERS]
    mediatype = "text/netlify"
    baseName = "_headers"
    isPlainText = true
    notAlternative = true
sectionPagesMenu = "main"
[Author]
  name = "René"
  email = "rene@renem.net"
[Params]
  description = "Just my 2 cents…"
  Paginate = 20
  RSSLimit = 25
  author = "René" # add your company name
  license = "CC-BY-NC-SA"
  github = "rretsiem" # add your github profile name
  twitter_name = "rretsiem" # add your twitter profile
  flickr_name = "renene26" # add your flickr username
  instagram = "rene.meister" # add your instagram username
  microblog_name = "renem"
  email = "rene@renem.net"
  ISO8601 = "2006-01-02T15:04:05+02:00"
  webSub = "https://renem.superfeedr.com/"
[sitemap]
  changefreq = "daily"
  priority = 0.5
  filename = "sitemap.xml"
[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
[[menu.main]]
        name = "Artikel"
        weight = 1
        identifier = "post"
        url = "/post/"
[[menu.main]]
        name = "Photos"
        weight = 2
        identifier = "photos"
        url = "/photos/"
[[menu.main]]
        name = "Microblog"
        weight = 3
        identifier = "microblog"
        url = "/microblog/"
[[menu.main]]
        name = "Archiv"
        weight = 4
        identifier = "archive"
        url = "/archive/"
[[menu.main]]
        name = "About"
        url = "/about/"
        identifier = "about"
        weight = 5
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.speakerDeck]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
  